name: pages build and deployment
on: workflow_dispatch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Generate and save GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site
      
      - name: Publish website on GitHub Pages
        uses: actions/deploy-pages@v1
